### ISSUE TITLE
read this

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyctaxi#1]
(http://chriswhong.com/open-data/foil_nyc_taxi/)

**Comment by beanumber** [comment]
Please read this @Akutix @letrangg

**Comment by beanumber** [comment]
Please collect other references on the Internet for use as "citations" in the vignette.

**Comment by beanumber** [comment]
Should we grab the live data instead? 

(http://toddwschneider.com/posts/analyzing-1-1-billion-nyc-taxi-and-uber-trips-with-a-vengeance/)

See these:
(http://www.nyc.gov/html/tlc/html/about/trip_record_data.shtml)
(https://github.com/toddwschneider/nyc-taxi-data/blob/master/raw_data_urls.txt)

**Comment by nicholasjhorton** [comment]
That's what I've been doing.  
Adding the uber data might be worth considering as well.

**Comment by beanumber** [comment]
@letrangg please change the URL in `etl_extract()` to pull directly the nyc.gov site.

**Comment by trangle157** [comment]
Professor,

I changed the URL and the codes for etl_load(), so now we could write to the database. Could you remind me how did we load the data into R last time, after writing it to a database? 

Best,
Trang

**Comment by beanumber** [comment]
@liwencong1995 these readings apply to you too!

**Comment by beanumber** [comment]
@liwencong1995 these references should be incorporated into the vignette.
