### ISSUE TITLE
submit to CRAN

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyctaxi#17]

**Comment by liwencong1995** [comment]
Email from CRAN:

Thanks, please add URLs for the Taxicab & Livery Passenger Enhancement Project and for the New York City Trip Data in your description text in the form
<http:...> or <https:...>
with angle brackets for auto-linking and no space after 'http:' and 'https:'.

Please fix and resubmit.

Best,
Swetlana Herbrandt
