### ISSUE TITLE
etl_load: the number of rows in MySQL is different from number of rows in r environment

### ISSUE THREAD

**Issue by liwencong1995** [beanumber/nyctaxi#28]
Left 2015 + 2016:
R:44455
MySQL: 44159

Uber 2014 + 2015:
R: 18804806
MySQL: 18442533

**Comment by liwencong1995** [comment]
The number of rows of `uber`, `lyft`, and `green` loaded into MySQL databases are different across databases.

**Comment by beanumber** [comment]
Why? Are there rows that are getting stripped out?

**Comment by beanumber** [comment]
This may or may not be a problem (https://stackoverflow.com/questions/11926259/why-is-the-estimated-rows-count-very-different-in-phpmyadmin-results)

**Comment by liwencong1995** [comment]
Used command line to get the number of rows. The number of rows for each month in MySQL matches the number of rows in the raw file.
