### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by liwencong1995** [beanumber/nyctaxi#29]
```
Error in .local(conn, statement, ...) : 
  could not run statement: Lost connection to MySQL server during query
```
According to this link, 
https://github.com/r-dbi/RMySQL/issues/190
In order to fix this issue, I might have to roll the RMySQL version back to 0.10.9.

The following code is needed in order to do that:
```
install_version("DBI", version = "0.5", repos = "http://cran.us.r-project.org")
install_version("RMySQL", version = "0.10.9", repos = "http://cran.us.r-project.org")
```

**Comment by beanumber** [comment]
@liwencong1995 can this issue be closed?

**Comment by liwencong1995** [comment]
I still get the same error when I try to run long queries or when I try to work with more than 10-month of taxi data. One solution is to only work with 6-month of taxi data at once.

**Comment by martinbel** [comment]
I'm getting the same issue using dbWriteTable. I'm trying to insert 522720 rows and 4 columns, not that much and it doesn't work. 
It works ok for 100 rows...

**Comment by beanumber** [comment]
@martinbel thanks for the feedback. Can you post a MWE so I can check it out?

**Comment by martinbel** [comment]
I ended up using another driver RMariaDB, it worked with the entire data.frame. Perhaps this is useful to see what's working there. 

Here are some example rows of the original data to reproduce the error. 
```

# here is a dtop() of the last rows.
df = structure(list(date = structure(c(18330, 18337, 18344, 18351, 
18358, 18365), class = "Date"), week_date = c("2020-W11-1", "2020-W12-1", 
"2020-W13-1", "2020-W14-1", "2020-W15-1", "2020-W16-1"), direction = c("destination", 
"destination", "destination", "destination", "destination", "destination"
), rt = c("OWY", "OWY", "OWY", "OWY", "OWY", "OWY"), state = c("WY", 
"WY", "WY", "WY", "WY", "WY"), branch = c("02599", "02599", "02599", 
"02599", "02599", "02599"), cpra = c("8341", "8341", "8341", 
"8341", "8341", "8341"), size = c("3", "3", "3", "3", "3", "3"
), variable = c("cr", "cr", "cr", "cr", "cr", "cr"), value = c(0.639292484453574, 
0.729868907491855, 1.05548060620358, 0.660385684705534, 0.630289908779409, 
0.664215921110822)), .Names = c("date", "week_date", "direction", 
"rt", "state", "branch", "cpra", "size", "variable", "value"), class = "data.frame", row.names = c(NA, 
-6L))

# just repeat the data several times
bigdf = do.call(rbind, lapply(1:10000, function(x) df))

# connect to your db, define con as usual.
dbWriteTable(con, name = "predictions", bigdf)

# then it gives
Error in .local(conn, statement, ...) : 
  could not run statement: Lost connection to MySQL server during query
```

**Comment by ben519** [comment]
Also experiencing this issue. My setup is as follows:

1. I have MySQL 5.7 set up on a [Google Cloud MySQL](https://cloud.google.com/sql/docs/mysql/) instance.  
2. I hit that database from
    1. a [Google Cloud VM](https://cloud.google.com/compute/docs/instances/) and 
    2. locally via my Macbook Pro

Using [RMariaDB](https://github.com/r-dbi/RMariaDB) I can read and write to the database from my VM and local machine without errors, although reading data to my local machine is [painfully slow](https://github.com/r-dbi/RMariaDB/issues/104).

Using RMySQL, I can read and write to the database from my local machine without issue. I can also read from the DB into my VM without issue. *However*, **when I try to write a large enough table of data from the VM to the database, I get a timeout error**.

Here's my small coded example
```
# Build connection
mycon <- DBI::dbConnect(
  drv = DBI::dbDriver("MySQL"),
  dbname = "mydb", 
  host = "11.111.111.111", 
  user = "foo",
  password = ""
)

# Write table 'iris'
system.time(RMySQL::dbWriteTable(conn = mycon, name = "iris", value = iris, row.names = FALSE, overwrite = TRUE))
# user  system elapsed 
# 0.008   0.000   0.042 

# Append a big table of data to the database (150K rows)
iris1000 <- vector(mode = "list", 1000)
for(i in 1:1000) iris1000[[i]] <- iris
iris1000 <- do.call(rbind, iris1000)

# Append (times out after ~30 seconds)
system.time(RMySQL::dbWriteTable(conn = mycon, name = "iris", value = iris1000, row.names = FALSE, overwrite = FALSE, append = TRUE))
# Error in .local(conn, statement, ...) : 
#   could not run statement: Lost connection to MySQL server during query
# Timing stopped at: 1.143 0.047 61.28

# Clean up
# RMySQL::dbRemoveTable(conn = mycon, name = "iris")
# RMySQL::dbDisconnect(mycon)
```

**Comment by beanumber** [comment]
@martinbel @ben519 It looks to me like your issues are with https://github.com/r-dbi/RMySQL/issues/190 and not with `nyctaxi`. Can you re-post your comments there? I'm sure other will want to see them.

**Comment by ben519** [comment]
Major derp on my part. Thought I was in RMySQL/ issues. Sorry!
