### ISSUE TITLE
expired SQLConnection and smart_download() stopped working

### ISSUE THREAD

**Issue by trangle157** [beanumber/nyctaxi#3]
I have two issues with etl_load() and etl_download(), the first one being expired SQLConnection (though R session restarted) and smart_download() does not download the data (I temporarily replaced with downloader::download to get the data in place first). To start analyzing the data, I will use a separate R script and link the table using src_sqlite() with the database populated before the connection expired.

**Comment by beanumber** [comment]
The SQLConnection will expire from time to time. You should be able to reconnect to it. We should add a function to `etl` called `reconnect()`.
