### ISSUE TITLE
data directory too large?

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyctaxi#30]
See also (https://github.com/beanumber/mdsr/issues/16)

I'm seeing that:
```
checking installed package size ... NOTE
  installed size is 18.8Mb
  sub-directories of 1Mb or more:
    data  18.0Mb
```
This is crazy, since none of the files are even close to that large. 
```
bbaumer@bbaumer-Precision-Tower-7810:~/Dropbox/git/sds192$ ls -lah ../nyctaxi/data
total 3.6M
drwxrwxr-x  2 bbaumer bbaumer 4.0K Nov 14 13:46 .
drwxrwxr-x 11 bbaumer bbaumer 4.0K Apr 12 11:12 ..
-rw-rw-r--  1 bbaumer bbaumer 1.5M Nov 14 13:46 green_2016_01_sample.rda
-rw-rw-r--  1 bbaumer bbaumer 3.3K Oct 31 13:48 taxi_zone_lookup.rda
-rw-rw-r--  1 bbaumer bbaumer 860K Oct 31 14:14 taxi_zones.rda
-rw-rw-r--  1 bbaumer bbaumer 1.3M Nov 14 13:46 yellow_2016_01_sample.rda
```
When the lazy-load DB gets built, I see:
```
bbaumer@bbaumer-Precision-Tower-7810:~/Dropbox/git/sds192$ ls -lah ~/R/x86_64-pc-linux-gnu-library/3.4/nyctaxi/data/
total 18M
drwxrwxr-x 2 bbaumer bbaumer 4.0K Apr 12 11:12 .
drwxrwxr-x 8 bbaumer bbaumer 4.0K Apr 12 11:12 ..
-rw-rw-r-- 1 bbaumer bbaumer  18M Apr 12 11:12 Rdata.rdb
-rw-rw-r-- 1 bbaumer bbaumer  128 Apr 12 11:12 Rdata.rds
-rw-rw-r-- 1 bbaumer bbaumer  211 Apr 12 11:12 Rdata.rdx
```

Why are two 1.5 Mb files becoming an 18 Mb database?? Does @rpruim know?

**Comment by rpruim** [comment]
Do you have cruft files on your system that are not in the repo?  Be sure to Rbuildignore them or delete them  if you don't want them included.

You can see the actual files used in the package (and their sizes) if you look at the tar ball that gets created when you build the package.  (Make sure you don't have old tarballs lying about -- those can greatly inflate your package size.)

**Comment by rpruim** [comment]
If you load your rda files and save them as csv (if that works for them), what size are they?

**Comment by beanumber** [comment]
> Do you have cruft files on your system that are not in the repo?

I don't think so. That's what I thought was going on. I expected to see a huge `.Rdata` file in the `data` directory, but there is no such file. 

> You can see the actual files used in the package (and their sizes) if you look at the tar ball that gets created when you build the package. 

The whole tarball is 4.4 MB, and I don't see any evidence of large files. 

> (Make sure you don't have old tarballs lying about -- those can greatly inflate your package size.)

Where would these be? 

> If you load your rda files and save them as csv (if that works for them), what size are they?

Well, they do take up a lot of memory when I load them into R:

```
> load("~/Dropbox/git/nyctaxi/data/green_2016_01_sample.rda")
> print(object.size(green_2016_01_sample), units = "Mb")
159.3 Mb
> load("~/Dropbox/git/nyctaxi/data/yellow_2016_01_sample.rda")
> print(object.size(yellow_2016_01_sample), units = "Mb")
361.7 Mb
```

Wait...that `green` data frame only has 100 rows and 21 columns...why does it take up so much space?
...
```
> str(green_2016_01_sample)
'data.frame':	100 obs. of  21 variables:
 $ vendorid             : int  2 2 2 2 2 2 2 2 2 2 ...
 $ lpep_pickup_datetime : Factor w/ 1044822 levels "2016-01-01 00:00:00",..: 973127 756964 600997 965737 889934 419519 289723 545341 478703 329512 ...
 $ lpep_dropoff_datetime: Factor w/ 1043109 levels "2016-01-01 00:00:00",..: 971212 755933 600200 964515 888261 418360 291976 544201 478349 328483 ...
 $ store_and_fwd_flag   : Factor w/ 2 levels "N","Y": 1 1 1 1 1 1 1 1 1 1 ...
 $ ratecodeid           : int  1 1 1 1 1 1 1 1 1 1 ...
 $ pickup_longitude     : num  -73.9 -73.8 -73.9 -74 -73.8 ...
 $ pickup_latitude      : num  40.7 40.7 40.8 40.7 40.7 ...
 $ dropoff_longitude    : num  -73.9 -73.9 -74 -73.9 -73.8 ...
 $ dropoff_latitude     : num  40.7 40.8 40.8 40.7 40.7 ...
 $ passenger_count      : int  1 1 1 1 1 1 5 1 1 1 ...
 $ trip_distance        : num  4.93 7.45 6 4.67 0.78 ...
 $ fare_amount          : num  15.5 22.5 18.5 20.5 5 4 73 5.5 19.5 5 ...
 $ extra                : num  0.5 0.5 0 0.5 0.5 0 0 0 0.5 0 ...
 $ mta_tax              : num  0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 ...
 $ tip_amount           : num  0 0 3.86 4.36 0 0 70 1.26 4.16 1.45 ...
 $ tolls_amount         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ ehail_fee            : logi  NA NA NA NA NA NA ...
 $ improvement_surcharge: num  0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 ...
 $ total_amount         : num  16.8 23.8 23.2 26.2 6.3 ...
 $ payment_type         : int  2 1 1 1 2 2 1 1 1 1 ...
 $ trip_type            : int  1 1 1 1 1 1 1 1 1 1 ...
```

Could it be the one million factor levels!?!?

**Comment by beanumber** [comment]
There is no reason to store that as a factor. @liwencong1995 I will fix this.

**Comment by beanumber** [comment]
@liwencong1995 File this under "Hazards of using `read.csv()` instead of `readr::read_csv()`"!

**Comment by rpruim** [comment]
Glad you were able to figure it out.  `drop.levels()` is another useful tool if you have subsetted data and don't want to retain levels no longer in the data.  (It can be applied to an individual factor or to an entire data frame.)
