### ISSUE TITLE
vignette - etl_init() - 'Could not find schema initialization script'

### ISSUE THREAD

**Issue by tbuckl** [beanumber/nyctaxi#31]
when i run:

```
taxi %>%
  etl_init()
```
from the main vignette on current master i get:

`Could not find schema initialization script`

**Comment by tbuckl** [comment]
i assume this sql init is just not a relevant chunk for this package because its already defined in the package.

**Comment by beanumber** [comment]
Correct. You can run it, but it will just use the `etl_init.default()` method from `etl`, defined here: (https://github.com/beanumber/etl/blob/master/R/etl_load.R#L105). 

There is no hard-coded SQL script for this package (yet).
