### ISSUE TITLE
vignette takes waaaaaay too long to compile

### ISSUE THREAD

**Issue by beanumber** [beanumber/nyctaxi#5]
We can't have the vignette actually download or load the data. It just takes too long. We will have to think of a different solution.

**Comment by trangle157** [comment]
Could we write a function to partly do the etl process (as a demo) ?

**Comment by beanumber** [comment]
How about having a small sample of the data (say, 1000 rows) in the package as an `.rda` file, and then use the `ext_extract.default()` method to process it?
